### PR TITLE
improved edgelist IO

### PR DESCRIPTION
**Pull request by bkj**
Load edgelists using pandas; symmetrize adjacency matrix w/ scipy operations.

Reduction in load time can be significant -- on 10M edge subset of `com-orkut.ungraph.txt`, reduces load time from 422s to 25s (94% reduction in run time)

Passed regression tests on various sample datasets.

### CODE REVIEW

**Comment by dgleich** [comment]
Can you comment on the change in memory requirements? One of the reasons for the old design was to minimize the extra memory required. (The switch to pandas reading is great!) 

The benchmark is we'd like to do 350M nonzeros (i.e. twice the number of edges) in 16GB of memory. 

I get a little worried with the manipulation of sparse matrices, which can easily balloon memory requirements. 

It'd also be good to replace the symmetric check with the sum with a small number of random mat-vec products with A and A'. (I want to add a from_adjacency_matrix() option too, so this would get reused there...) It's very possible (due to common graph constructions) that you'd have equal row/column sums, but not actually be symmetric, this would protect us against that silly case. [Yes, I realize it's not full protection :) ]

**Comment by bkj** [comment]
Do you have an example of graph where you were going over 16GB using the previous method?  (The full ORKUT matrix is < 3GB as a CSR.)  Presumably a graph of that size would take many hours to load?

I'm not sure I understand what you mean about the randomized symmetry check.  I'm doing an exact symmetry check right now -- I personally wouldn't want to use a randomized algorithm unless I really had to (and I certainly wouldn't want to default to one).

FWIW, if you're only going to handle undirected graphs, I would just assume that the input graphs are properly formatted and maybe provide a utility for converting an arbitrary graph to the format you care about.  Then you could make these loading operations much faster and the cost of the initial transformation is amortized over all the subsequent local graph clustering runs.

**Comment by kfoynt** [comment]
Here is a small benchmark that I did

(Ben's) 9.4GB and 158 seconds
(Ben's without symmetry check) 5.83GB and 65 seconds
(Ours) 5.34GB and 2600 seconds

I think will use Ben's without the symmetric check.

**Comment by dgleich** [comment]
Okay, great! we should add another issue to add a randomized symmetry check
to optimize that step.

In terms of Ben's reply (sorry, typing from email, so no fancy Github @),
my experience has been that NO one gets input formats correct. (Myself
included...) being robust to these inputs and converting them to our format
is essential, but we want to be as memory efficient as is reasonable.

**Comment by kfoynt** [comment]
Hi David,

I brought back symmetry actually for the reason that you mentioned. I do not trust the users. 
Also, even if they do add the correct input the total memory requirement would have been about the same. 

I think our previous solution using list_to_CSR was probably not ready for wide use because it was very slow, although very cool!
Maybe if we implement this in C this will speed up list_to_CSR so it is comparable to Ben’s solution? 
I would prefer that if possible because it has half the memory requirements, i.e., 5GB vs 10GB.

Kimon

**Comment by bkj** [comment]
Yes -- definitely agree that no one gets the input formats correct.  And definitely shouldn't trust the users 😄 

I generally prefer checking the format and throwing an error if there's something wrong a) so that expensive checks don't have to happen every time the graph is loaded and b) because for very large graphs I often do the preprocessing in Spark or something else with a lot of horsepower.  Also, converting a directed graph to an undirected one sometimes involves some kind of domain-specific transform (should you take max weight? min weight? add the weights? etc.)

Up to you guys how you'd like to handle it though -- LMK if there are any changes to the code you need from me.

~ Ben

**Comment by kfoynt** [comment]
Hi Ben,

> I generally prefer checking the format and throwing an error if there's something wrong
> 
> 

Even if we do this the memory problem will to transferred to a different place, i.e., the data file. 
Since it is generally accepted that in an edgelist for undirected data we do not store all edges I assume that users 
would expect their input to have this property. So, I will stick for now with your symmetry check + symmetrization. 

> Also, converting a directed graph to an undirected one sometimes involves some kind of domain-specific transform (should you take max weight? min weight? add the weights? etc.)
> 
> 

This happens currently only for gml or graphml. They that it is handled is based on networkx: 
https://networkx.github.io/documentation/networkx-1.10/reference/generated/networkx.Graph.to_undirected.html <https://networkx.github.io/documentation/networkx-1.10/reference/generated/networkx.Graph.to_undirected.html>

Kimon

**Comment by kfoynt** [comment]
Sorry for the typos!! :-D

**Pull request merged**
