### PR TITLE
first version of standard drawing method

### PR DESCRIPTION
**Pull request by MengLiuPurdue**

### CODE REVIEW

**Comment by dgleich** [comment]
Meng, can we rip out the use of networkx drawing and just use our routines? Also, the return values for nodelist/etc are the list of nodes, not the actual handles to the plot elements.

**Comment by MengLiuPurdue** [comment]
@dgleich Let me know how you feel on the new template.

**Comment by dgleich** [comment]
Okay, this is coming along!

We still need stuff to visualize a vector of entries over the nodes, e.g. a fiedler vector or ACL vector. 

I don't like how you are creating a vector of colors, that seems like it could be done more efficiently. (And allow for colormap scaling, etc.)

Groups should also take in a partition vector (e.g. each key is a group, in addition to a group-of-groups)

**Comment by MengLiuPurdue** [comment]
@dgleich 
Let me know if the latest commit solves the first two issues (except the groups).

**Comment by dgleich** [comment]
I'll start playing around with it. It looks very brittle thought. Also, we
are still not returning the right things...

We need to return handles to the plot elements so that someone can change
them after the fact. e.g. if I want to make nodes bigger/smaller, etc.

Also, what does draw_star do?

David

**Comment by MengLiuPurdue** [comment]
@dgleich I am not very sure how to return plot handles... Is there a simple example I can refer to? "draw_star" is just plot all the edges connect to a specific node, like a star.

**Comment by dgleich** [comment]
Things I know we want to do.

0. Draw a graph with a given set of coordinates. (Flexible edge 
alpha, node alpha, node color, line color, line widths, etc., node sizes,)


1. Draw a graph and highlight a set of nodes.

2. Draw a graph and show values over the nodes (possibly a sparse set)
3. Draw a graph and highlight both a set and values.
4. Draw a graph with groups/clusters
5. Draw a grah with groups/clusters and highlight a set. 

For all the plot elements, we should be able to customize sizes, 
transparency, and colors. 

Does it make sense to draw groups and a set of values over the graph?



Other 
5. 

G = lgc.GraphLocal()
elems = G.draw(coords)
elems = G.draw(coords, nodeset=S)
elems = G.draw(coords, values=v, nodeset=S)

elems = G.draw_groups(coords, g)
elems = G.draw


---



G = lgc.GraphLocal()

drawing = G.draw(coords)
drawing.highlight(set)
drawing.edge_linewidth

drawing = G.draw(coords, values=fiedler(G)[0], valuecenter = 0, colormap=PuOr)

drawing.highlight(set, othernodes=False, otheredges=False) # hide other nodes and edges
drawing.highlight(set, othernodes=False) # hide other edges

drawing = G.draw(coords, values=v)
drwaing = G.draw(coords, values=v, sizes=s

drawing = G.draw_groups(coords, g, sizes=s)
drawing.highlight(set)
drawing.between_group_alpha(0.5)

drawing.highlight(set, filled=False) # only circle the nodes

drawing.nodecolor(i,c=None)  # returns the current nodecolor
drawing.nodecolor(i,c=[
drawing.edgecolor(i,j,c=None)


----

class GraphDrawing
    def __init__(self, G, coords, ax):
        self.G = G
        self.coords = coords
        self.is_3d = len(coords[0]) == 3
        self.edgepos = self._build_edgepos(G)
        if ax == None:
            fig, ax = plt.subplots()
        else:
            fig = ax.get_figure()
        self.ax = ax
        self.fig = fig
        
        nodes = ax.scatter()
        edges = LineCollection()
        
        
        
    def show(self):
        return fig

----

drawing = G.draw(coords)
drawing.show() # this returns the figure, to show it in a Jupyter window, for instance

----

drawing = G.draw(coords, ax = ax)

**Comment by MengLiuPurdue** [comment]
@dgleich There are still a lot of details to finish, but I'd like to show you the structure and some examples in "new_visualization_examples.ipynb". Let me know how you feel about it.

**Comment by dgleich** [comment]
Okay, I think this is getting there...!

I think we should simplify the interface to draw. I don't think it should
take a nodeset now. If you want a nodeset, then you should highlight that
explicitly.

I think there are two fundamental routines.

g.draw(values, sizes, etc...)
g.draw_groups(groups, sizes, etc...)

so in the second case, we handle all the group stuff, and in the first
case, we don't.

Given the return value from either, we should be able to highlight a set.

David

**Comment by MengLiuPurdue** [comment]
@dgleich I am not sure what ax._sci() does. Do you have a small example?

**Comment by dgleich** [comment]
See this -- https://matplotlib.org/api/_as_gen/matplotlib.pyplot.sci.html

David

**Comment by dgleich** [comment]
Okay, why were the two bioinformatics notebooks deleted?

Do we need the "class" files and such? Why can't we just use the GraphML like we used to? If we need them, can you store the info as integers and lower-precision floats? These take up a lot of space!

Also, the job seems to have failed :)

**Comment by MengLiuPurdue** [comment]
@dgleich Those two were deleted because I have rewritten them using the new interface. If we stick to the original GraphML, it will take more code and even have to use graph_tools to extract the ground truth. To make the examples more clear, I decided to save the class info into a separate file so that we can read them in one line. But I will use some other data type to save the space. And yes, the job probably failed due to the new MQI code, I haven't tested it throughly.

**Comment by dgleich** [comment]
We depend on Networkx already, can't we use their GML reader and the
from_networkx function ?

**Comment by MengLiuPurdue** [comment]
@dgleich We can, but my point is in the original notebook, taking ppi_mips as an example, it still needs three files ppi_mips.graphml, ppi_mips_coordinates.xy and ppi_mips_ground_truth.csv to get the graph, its layout and the ground truth. Also, it needs some additional code to preprocess the coordinates and ground truth file which makes the example less cleaner. Right now, the new notebook needs ppi_mips.graphml, ppi_mips.xy and ppi_mips.class and it doesn't need any preprocessing at all. So we can safely delete ppi_mips_coordinates.xy and ppi_mips_ground_truth.csv.

**Comment by dgleich** [comment]
I guess I like that code because anyone else who uses our stuff will have
to go through a similar process to use their data. So it's helpful to have
an example that shows it :)

David

**Comment by kfoynt** [comment]
Btw, are there any examples of this in the notebook folder?

**Pull request merged**
